### ISSUE TITLE
more flexibility in window sizing would be nice

### ISSUE THREAD

**Issue by aspiers** [acarabott/tabToWindow#1]
Hey Arthur :) Only just got around to looking at this - very cool, I have been wanting this kind of thing for quite a while.  Would be great if it was possible to configure it so that the original window size is preserved, and also that the new window size can be a clone of the original.  Bonus points for making these available as independent options ;-)

**Comment by acarabott** [comment]
Only 16 months later... b6db6b6c6216c808e3d56728f563c3352390b8e0

**Comment by aspiers** [comment]
Excellent, thanks! Will you release this new version to the chrome web store?

**Comment by acarabott** [comment]
It should be up there now :)
