### ISSUE TITLE
Focus on New Tab After  Popout Doesn't work on Linux

### ISSUE THREAD

**Issue by Mingling94** [acarabott/tabToWindow#14]
At least not on mine.
OS: Ubuntu-Gnome 14.04
Chrome Browser

**Comment by acarabott** [comment]
Did your pull request fix this?

**Comment by Mingling94** [comment]
Oh sorry, I should clarify. This issue occurs when popping the tab OUT of the window. My PR #13 dealt with tabs popping back in.

**Comment by acarabott** [comment]
Just to check, you have `Focus on new tab` checked in options?

**Comment by Mingling94** [comment]
Oh snap, sorry bout that! I assumed the extension options would transfer between my OS partitions via Chrome. Silly me!
