### ISSUE TITLE
Remove Scrollbars in Popups

### ISSUE THREAD

**Issue by MartinLichtblau** [acarabott/tabToWindow#17]
A popup with scrollbars is like material design with comic sans, it's a major design flaw. You use these popus to have a clean view on your content and then you have such big scrollbars all over it. 
Since Windows 10 doesn't have any borders anymore *(yeeah!, it was time)* it looks even cooler when you remove the scrollbars. 

And c'mon who scrolls with scrollbars?
![popup](https://cloud.githubusercontent.com/assets/4956334/9086286/d1b1c3b8-3b83-11e5-97ba-b575594b3f9e.png)

**Comment by acarabott** [comment]
Haha, love your enthusiasm.

I can't see scrollbars in your screenshot, is that the point?

I think this is more of an OS level issue: on OS X they hide automatically if you are using a trackpad, but on an operating system where you don't expect this, you lose the signifier that there is more content.

I think you may just want [this plugin](https://chrome.google.com/webstore/detail/no-scroll-bars-please/ahnbemfjhoibkhlijfbbjdjafbmhimdn?hl=en)

**Comment by MartinLichtblau** [comment]
:D I already have this plugin and that's why I have no scrollbars.
Furthermore I reduced the global scrollbar since in windows so also the hardcoded scrollbars in chrome are very thin. 

If you have set everything to default it looks like this in a small window (The bars won't auto hide) 
![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3838363035392f313538383030382f34323838636462362d353234372d313165332d383036612d6432356439316134306333372e706e67](https://cloud.githubusercontent.com/assets/4956334/9104827/23ca1424-3c11-11e5-944e-6d8fbdfa2db4.png)

But you are right, it's no must have.

**Comment by acarabott** [comment]
Scrollbars being an OS issue, this is outside scope of this plugin.
