### ISSUE TITLE
tabToWindow not working

### ISSUE THREAD

**Issue by OliverPedro** [acarabott/tabToWindow#19]
I downloaded and installed your extension but it is not working. Please can you help out?

**Comment by acarabott** [comment]
Which OS are you using? 
Can you go to chrome://extensions/ scroll down to the bottom and click 'Keyboard shortcuts' and check that you have some set?

**Comment by OliverPedro** [comment]
Thanks for answering
 
Windows 10, 
I tried all ways at the “keyboard shorcuts”... and nothing works
 

	
		

 
Thanks!!

**Comment by acarabott** [comment]
I have published a small update to this. Can you restart Chrome, make sure you have version `2.2.6` and try again?

**Comment by OliverPedro** [comment]
great! now it works!
would it be difficult to add that before opening that, the current window goes half window so as the new one opens at the other half window?

**Comment by acarabott** [comment]
This is totally already possible! Check out the options screen for the plugin and you can set the size and position for the windows to take!

**Comment by OliverPedro** [comment]
thanks so much!

**Comment by OliverPedro** [comment]
what's going on?
when I press the shortcut it is opening but the previous window and not the exact window

**Comment by acarabott** [comment]
it was working correctly before right?

I wonder if chrome/Windows has updated and something has changed.

I am away for a couple of weeks, so probably can't look at this immediately. Afraid there's no company behind this plugin!

**Comment by OliverPedro** [comment]
The way it worked is very rare; AT LEAST it opens not exactly the same window but a previous one; but it seems that once it is done, that it cannot be repeated, 

or even reopening Chrome it is not working at all

if you can at it some time I would appreciate 

thanks

**Comment by acarabott** [comment]
I am wondering if there is something unusual happening. Can you copy paste names of all other extensions you have for chrome?

**Comment by OliverPedro** [comment]
enclosed two screenshots
please let me know if you receive this email
 
I’m not an expert... I’d not know how to copy these at GitHub website forum
thanks!!!

**Comment by acarabott** [comment]
I can't see the screenshots, want to mail to me? arthurc gmail

**Comment by OliverPedro** [comment]
enclosed are the screenshots, thanks!

**Comment by acarabott** [comment]
Attachments are removed by github, can you e-mail them to me directly: arthurc gmail com
