### ISSUE TITLE
Is there a way to get rid of tabs completely?

### ISSUE THREAD

**Issue by balzss** [acarabott/tabToWindow#22]
I really need a tool like this but which forces ALL the tabs to a pop-up window and basically never lets to have any tabbed window.

**Comment by acarabott** [comment]
You're saying each tab to it's own pop-up window? e.g. 

` 1 window with 10 tabs -> 10 pop-up windows `

**Comment by balzss** [comment]
yes, exactly

**Comment by acarabott** [comment]
Hmm I think this is out of the scope of this extension. You are very
welcome to fork the sourcecode and make it yourself though!
