### ISSUE TITLE
Tab not maximized when sending to window.

### ISSUE THREAD

**Issue by emilioidk** [acarabott/tabToWindow#23]
Hi.

I have the extension set up to open the tab in a new window and focus the new window. It is supposed to clone the original window size as well. Shouldn't the tab be maximized if the original window is maximized?

**Comment by acarabott** [comment]
Hi,

(Apologies for delayed reply, I was finishing my masters)

By maximised do you mean full screen? Are you on Windows / Mac / Linux?

It currently doesn't copy the maximise property, will consider this for the next update.

**Comment by emilioidk** [comment]
Hi,

Congratulations with your masters!

I did mean "Full screen" with maximized. I am on Linux but a friend of mine uses it on Windows and told me he experiences the same thing. 

Thanks for creating and maintaining the extension, it is quite useful :+1:

**Comment by acarabott** [comment]
fixed by b216de5cfb5e6f8b8eadacbd02017935e5db049c
