### ISSUE TITLE
Automatic focus for new window?

### ISSUE THREAD

**Issue by DamSenViet** [acarabott/tabToWindow#24]
It's kind of jarring to keep focus on the same window. Might it be possible to make it so that it automatically focuses on the popped up window?

**Comment by acarabott** [comment]
That's an existing option! Check out the settings page:
<img width="920" alt="instructions" src="https://user-images.githubusercontent.com/66132/27862419-f6e0eb16-617c-11e7-846c-f9078d22c3eb.png">
