### ISSUE TITLE
Pop a single tab

### ISSUE THREAD

**Issue by ekilah** [acarabott/tabToWindow#28]
First off, thanks for making this, it's useful!

If I already have a window open with a single tab, I can't use the plugin to make it a pop-up it seems. The current workflow seems to require:

1. Ctrl+T to make a new tab I don't need (2nd tab in window, first tab is the one I care about)
1. Ctrl+Shift+Tab to switch back to 1st tab since Chrome switches the focus when you make a new tab
1. Use shortcut to make pop-up
1. Go back and close the window left with the new tab I didn't want
  

edit: at least, it seems intentional - maybe there is some limitation where this is necessary but figure'd I'd ask. https://github.com/acarabott/tabToWindow/blob/a2902dce27a639e77fb86e9c8eee09a21bd3e43d/js/ttw.js#L192

**Comment by acarabott** [comment]
Thanks for using it!

Hmm, that's a use case I had never considered, that someone just wanted a pop-up window. My usage was always to see two windows simultaneously without messing around.

I'm currently refactoring a lot of the code, so I'll add this as a feature to do.

**Comment by acarabott** [comment]
Fixed in 3f1105a8c710d8b6ff08b836cfcd1583247b36c6 (release soon)

**Comment by ekilah** [comment]
awesome, glad I could help!
