### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by acarabott** [acarabott/tabToWindow#3]

**Comment by phillipchan2** [comment]
This would be very nice to get multiple monitor support. People who use this are probably big multitaskers and probably have multiple monitors.

**Comment by acarabott** [comment]
I really want to get multi monitor support built. I'm interested in how you would want it to work, do you think you could describe how you imagine it being most useful?

**Comment by phillipchan2** [comment]
So I have ~2-3 monitors at work on OS X El Capitan. When i “pop out” a window on a secondary monitor, it moves the tab out successfully, but it will move both original and new window to the “primary” monitor. I feel like it should stay on the monitor it was popped out from so I don’t have to move it back to the monitor it was on. 

This post seems to suggest the window.moveTo method limits the move to a singular monitor
https://bugs.chromium.org/p/chromium/issues/detail?id=234132

You might have done more research on methods available to make it work than I did. 

-- 
Phillip Chan


On February 29, 2016 at 3:07:46 PM, Arthur Carabott (notifications@github.com) wrote:

I really want to get multi monitor support built. I'm interested in how you would want it to work, do you think you could describe how you imagine it being most useful?

**Comment by acarabott** [comment]
One thing you could do is disable resizing of the original window in the extension options.

You could also set the popped window to clone the size of the original window, and it will position itself either on top of, or just next to the original window.

Could you try that and then see how far it is from your ideal behaviour?

**Comment by phillipchan2** [comment]
Yah, it seems that the resize method automatically moves it to the primary monitor. Disabling it allows it to pop out in the current monitor. This is better. 

Thanks!


On March 1, 2016 at 10:51:25 AM, Arthur Carabott (notifications@github.com) wrote:

One thing you could do is disable resizing of the original window in the extension options.

You could also set the popped window to clone the size of the original window, and it will position itself either on top of, or just next to the original window.

Could you try that and then see how far it is from your ideal behaviour?

**Comment by Shrulik** [comment]
I would like something where I turn the tab into a window, and it also moves the new window to another screen, for start it can be in full size/same size, but possibly the shortcut will determine the size of the resulting window on the other monitor.

There is the issue of more than two monitors, but at first, I think it should be non-primary -> primary, primary -> left to primary ( changeable in settings to right ).

 I might look into this myslef in a few weekends.

**Comment by acarabott** [comment]
I'd welcome any work towards this :) In the middle of a masters project at the moment, so don't have any time to dedicate.

**Comment by acarabott** [comment]
fixed in 7992ab711a388210f13a61d0130ef36c92124098 (will be released shortly)
