### ISSUE TITLE
Add option to disable context menu entry on pages

### ISSUE THREAD

**Issue by DanH42** [acarabott/tabToWindow#38]
I use this extension exclusively via keyboard shortcuts, so it's weird seeing it show up any time I right-click on a page. It would be nice if that could be turned off in the extension's settings.

**Comment by acarabott** [comment]
Hi Dan, thanks for your comment.

I'm with on being a heavy keyboard user, but had enough people request mouse interactions that I obliged. 

I currently don't see the one extra item in the context menu as being significant enough to warrant the increase in code. I'm the only person contributing to this plugin, and would rather keep it as maintainable as possible.

If you can provide a pull request then I'll see about integrating it.

Cheers,

Arthur

**Comment by dimateos** [comment]
Hey!

Im also interested in this, so subsribing to the issue.

A single extra entry is ok, but many extensions tend to add them without option to disable it and then the ones I often use end up surrounded.

Thanks for the extension!
