### ISSUE TITLE
Tab to Window does not resize original window if maximized

### ISSUE THREAD

**Issue by lustricker** [acarabott/tabToWindow#44]
### Description
When executing the command `Tab to Window` the original window is not resizing and aligning next to the window which has been docked away.
It works when the original window is not **maximized** but in a resized state.

### See the following video for understanding:
![ED035A5A-D189-4B09-9985-4FFD41A2F182](https://user-images.githubusercontent.com/56259521/72971849-b35b1380-3dca-11ea-9eae-8370f90494ac.GIF)

### My settings are the following:
![settings](https://user-images.githubusercontent.com/56259521/72971507-15ffdf80-3dca-11ea-849b-d35566ec187a.JPG)

**Comment by madmaxlax** [comment]
+1

I am on windows 10, and checking or unchecking "keep fullscreen status" does not make a difference, 

if the orig window is big but not full screen, it does successfully resize the original windows how you tell it, so it seems just to be an issue with the full screen original

**Comment by madmaxlax** [comment]
@acarabott  I just PR'd a fix, it's a quick one 
if a window is in full screen, it ignores any new sizes, you need to set the window from 'fullscreen' to 'normal'
https://github.com/acarabott/tabToWindow/pull/51

**Comment by acarabott** [comment]
This is now fixed in `3.2.2` we just have to wait for Google to approve it...
