### ISSUE TITLE
v3.2.0: Hotkeys no longer function on OS X

### ISSUE THREAD

**Issue by bongardino** [acarabott/tabToWindow#47]
Chrome: Version 80.0.3987.87 (Official Build) (64-bit)
OS X: 10.14.6

No conflicting hotkeys, last confirmed to be functional on 2-7-20.  Let me know if there's any other info I can provide

**Comment by acarabott** [comment]
Apologies for this, this has been fixed in `3.2.1` which has just been approved. 
There's now an annoyingly long approval process for each release.
