### ISSUE TITLE
Need to press shortcut keys twice

### ISSUE THREAD

**Issue by BackSeat** [acarabott/tabToWindow#50]
Maybe this is a PEBKAC issue, but if it is I'd appreciate any suggestions for resolving it.

I have the keyboard shortcut Ctrl+Shift+W to split a tab off to its own window. Some time ago, I found I needed to type that sequence twice to get the tab to detach. I still do. On the second time of typing, it works flawlessly.

Any suggestions for working out what going on?

**Comment by acarabott** [comment]
Interesting. My first guess would be window focus, that perhaps the tab is not fully focused. I sometimes find this is an issue, and that clicking on the page first makes it work (this is annoying but I believe out of my control).

Could you try that and let me know if it works first time after clicking on the page?

**Comment by BackSeat** [comment]
Thanks, but definitely not that. I have focus follows mouse, so focus is there anyway. Just tried clicking on the page first, then typing the shortcut, but I still needed to type it twice. I've also tried changing the shortcut key, but no difference.

Anything I can do to help isolate this?

**Comment by acarabott** [comment]
Could you let me know your operating system?

**Comment by BackSeat** [comment]
Linux, Debian 10.4

**Comment by richarddbarnett** [comment]
I'm affected by this too.
* macOS Catalina 10.15.4
* Chrome 81.0.4044.138 (Official Build) (64-bit)

Perhaps it's due to interaction with another extension?

**Comment by BackSeat** [comment]
I have tried changing the shortcut key I use (was shift-ctrl-W, now shift-ctrl-Q). The behaviour persists and I still have to type it twice.

**Comment by acarabott** [comment]
Yes I am noticing this too now, and it is somewhat new. I think the extension may not be "activated" on the first press, as I find that all subsequent presses only need one keypress and not too. Will investigate...

**Comment by acarabott** [comment]
I have submitted a fix for this, just waiting for Google to approve, check for version **3.2.3**.

Let me know if the issue persists.

**Comment by BackSeat** [comment]
Fixed for me, thank you.

**Comment by richarddbarnett** [comment]
Also fixed for me. Thanks!
