### ISSUE TITLE
Support new Edge browser

### ISSUE THREAD

**Issue by acarabott** [acarabott/tabToWindow#52]

**Comment by ojintoad** [comment]
fwiw worked for me mostly on microsoft edge chromium

![image](https://user-images.githubusercontent.com/3084796/88483743-e3c96900-cf37-11ea-9fe1-f847637016a9.png)

**Comment by acarabott** [comment]
Great to know, any particular issues?

Thanks for the coffee!

**Comment by xCuri0** [comment]
@acarabott the windows appear to not have a small gap between them wasting screen space

**Comment by tinywrkb** [comment]
@acarabott please consider publishing in the Edge addons store.  
Installing extensions from the Chrome store is a browser setting in Edge so it's not being synced with the MS account.  
Having the extension in the Edge store will make sure it will be deployed automatically to a clean profile after the user logged in to the MS account.  

I tested the extension with the latest Edge 91 beta on Linux, only when running as a native Wayland client (Ozone), I haven't bothered with X11, and it seems to be working fine, nothing is broken as far as I can tell.

**Comment by acarabott** [comment]
I have just paid for a Microsoft account and submitted the extension for review. Fingers crossed this is all smooth, as my availability for support is minimal these days!
