### ISSUE TITLE
Tab to next/previous window does not work with Google Drive, Sheets, or Github

### ISSUE THREAD

**Issue by dannypernik** [acarabott/tabToWindow#71]
Hi, thank you for the amazing tool. Unfortunately, my Tab to next/previous window shortcuts are not working while a Google Drive or Sheets tab is active. I'm seeing now it doesn't work with Github tabs either. I've tried Cmd + shift + K/L, ctrl + shift + K/L, and option + shift + K/L. In all shortcut variations, the active window switches, but the tab does not come along for the ride.

In this screen recording, you can see the keyboard shortcuts I'm using in the lower left corner:

https://github.com/acarabott/tabToWindow/assets/3347095/08e8a5d2-8cae-4fa3-91c8-c84f9a45a4e7

**Comment by acarabott** [comment]
I have just tried with Github, Google sheets, and Drive using the short cuts `alt z` and `alt shift z` for next / prev; all are working.

If you try those shortcuts do they work for you? That would be a clue that perhaps something else is interfering with Chrome's shortcut handling.

**Comment by dannypernik** [comment]
@acarabott I don't know what the deal was, but those sites are working fine with my original shortcuts. I'll let you know if I experience it again, but closing for now. Thanks!

(Best guess is a conflict with another extension. I've tried number of keyboard shortcut-related extensions recently.)
